### ISSUE TITLE
Any way to provide our own DB connection info?

### ISSUE THREAD

**Issue by tfmm** [rhythmictech/terraform-aws-awx#19]
We have a robust DB Architecture in place already, and I'd rather provide DB connection info than spin up another RDS instance. How difficult would it be do do this?

**Comment by sblack4** [comment]
Not very. You could just clone this repo, delete the `database.tf` file, and switch any `module.database` references to reference variables containing this info about your database. There might be a few things you need to do so the secrets and IAM permissions work right but that's about it.
